import styles from "../styles/Home.module.css";
import { RevalidateButton } from "../components/RevalidateButton";
import Link from "next/link";
import { getResolvedUrl } from "../utils";

export default async function Page() {
  const resolvedURL: any = await getResolvedUrl(
    "https://source.unsplash.com/random/"
  );
  console.log("resolvedURL", resolvedURL);

  return (
    <main>
      <p className={styles.description}>
        To see the on-demand revalidation results, build first then visit un
        revalidated pages.
        <br />
        <code className={styles.code}>yarn build && yarn start</code>
        <br />
        <br />
        Then visit page like <code className={styles.code}>/dog</code> or{" "}
        <code className={styles.code}>/cat</code>.<br />
        It will make another caches for each page in the{" "}
        <code className={styles.code}>.next</code> folder.
        <br />
        <br />
        Util it is revalidated, it will use the cached version. (It will show
        the same dog & cat image.)
      </p>

      {/* <div style={{ display: "flex", gap: 12, padding: 50 }}>
          <Link href="/dog">Go to dog</Link>
          <Link href="/cat">Go to cat</Link>
        </div> */}

      <RevalidateButton />
      <img src={resolvedURL} style={{ width: "100%" }} />
    </main>
  );
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};
